site_name: aspen
theme: readthedocs
repo_url: https://github.com/RD-Processa/Aspen

pages:
- Introducción: index.md
- Registro de aplicaciones: App_Register.md
- Asegurar una clave API: Securing_AppKey.md
- Identificación de aplicaciones: App_Setup.md
- Pasos para crear un JWT : JWT-Build.md
- Solicitar un token de autenticación: JWT-Request.md
- Generar un token de autenticación: Generate-Token.md
- Enviar un token de autenticación: Send-Token.md
- Cambiar el secreto de una aplicación: Update-AppSecret.md
- Tokenización de pagos: Tokenization.md
- Canales para tokens de pago: Get-Channels.md
- Generación de un token de pago: Generate-PaymentToken.md
- Validación de un token de pago: Redeem-PaymentToken.md
- Mensajes de respuesta: Responses.md
